version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=cws_db"
      - "POSTGRES_USER=cws_user"
      - "POSTGRES_PASSWORD=cws_password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
