version: '2.4'

services:
  postgres:
    image: postgres:alpine
    environment:
      - "POSTGRES_DB=cws_db"
      - "POSTGRES_USER=cws_user"
      - "POSTGRES_PASSWORD=cws_password"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cws_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # NOTE: docker-compose up service check workaround. docker-compose not waiting for
  # service started condition
  wait:
    image: alpine:latest
    depends_on:
      postgres:
        condition: service_healthy
